### ISSUE TITLE
Issue with spawn nodes

### ISSUE THREAD

**Issue by swapmasterx** [potassium-shot/godot-untrue#1]
Having trouble getting the spawn nodes to work as the game keeps spawning me at the world origin

**Comment by potassium-shot** [comment]
Hello, was it inside a 3D or a 2D project?

**Comment by potassium-shot** [comment]
Okay, just found and fixed the issue. It won't be live on the asset lib right away as the moderators have to accept it, but it is on the latest commit of this repo. Thanks for pointing out the issue, and don't hesitate to tell me if it persists.
