### ISSUE TITLE
Not sure what these are...

### ISSUE THREAD

**Issue by Shadowblitz16** [potassium-shot/godot-untrue#3]
What is all this? How should I set up a main menu?
![image](https://github.com/potassium-shot/godot-untrue/assets/2453707/4a4b2bd9-2a77-43d3-9a93-d1ff9d0ce8aa)

**Comment by potassium-shot** [comment]
Hello @Shadowblitz16 , I highly encourage you to check the demo project of this repo to have an example usage of the GameRoot.

The level root is where Levels are going to be instanced, and the hud root is where the ui is going to be placed (useful if you want to put it in a canvas layer for example)

To make a main menu, I'd make an empty level with a gamemode that has the main menu scene as the hud. No player, no camera etc. And then set the Default level path of the GameRoot to it.

Keep in mind that levels need to be saved scenes in the filesystem, with LevelRoot as their root node.

**Comment by Shadowblitz16** [comment]
@potassium-shot what about the transition animation player property?
How do I tell it what animation to play?

Oh I think I see it under game root's default level transition.

But I can't find your demo, I need to know how to statically type level and gamemode transitions

**Comment by potassium-shot** [comment]
[This scene](https://github.com/potassium-shot/godot-untrue/blob/master/game_root.tscn) is the Game Root of the demo. The transition animaton player can be any animation player; when you call `Game.get_game_root().transition_to_level("res://level/path.tscn", "transition_name")`, it will play that animation.

It will try to play "transition_name_start" and "transition_name_end" for the transition start and end, but if those don't exist, it will try to play "transition_name" and then "transition_name" backwards.

This can be found in the in-engine doc for the GameRoot node.

I'm not sure what you mean by statically type level and gamemode transitions.
